[package]
name = "AptosFormsDemo"
version = "0.0.1"

[addresses]
aptos_forms_demo = "_"
xrender_form_utils = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "aptos-cli-v1.0.11" }
XRenderFormUtils = { git = "https://github.com/dddappp/XRender-Form-Utils.git", subdir = "aptos-move", rev = "main" }
