// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_forms_demo::aptos_forms_demo2_global {
    use aptos_forms_demo::aptos_forms_demo2_genesis_account as genesis_account;
    use aptos_forms_demo::aptos_forms_demo2_pass_object as pass_object;
    use aptos_framework::account;
    use aptos_framework::aptos_coin::AptosCoin;
    use aptos_framework::coin::Coin;
    use aptos_framework::event;
    friend aptos_forms_demo::aptos_forms_demo2_global_deposit_coin_claimer_1_vault_logic;
    friend aptos_forms_demo::aptos_forms_demo2_global_withdraw_coin_claimer_1_vault_logic;
    friend aptos_forms_demo::aptos_forms_demo2_global_admin_withdraw_coin_claimer_1_vault_logic;
    friend aptos_forms_demo::aptos_forms_demo2_global_aggregate;

    const EDataTooLong: u64 = 102;
    const EInappropriateVersion: u64 = 103;
    const ENotInitialized: u64 = 110;

    struct Events has key {
        coin_claimer_1_vault_deposited_handle: event::EventHandle<Coin_claimer_1_VaultDeposited>,
        coin_claimer_1_vault_withdrawn_handle: event::EventHandle<Coin_claimer_1_VaultWithdrawn>,
        coin_claimer_1_vault_admin_withdrawn_handle: event::EventHandle<Coin_claimer_1_VaultAdminWithdrawn>,
    }

    public fun initialize(account: &signer) {
        genesis_account::assert_genesis_account(account);

        let res_account = genesis_account::resource_account_signer();
        move_to(&res_account, Events {
            coin_claimer_1_vault_deposited_handle: account::new_event_handle<Coin_claimer_1_VaultDeposited>(&res_account),
            coin_claimer_1_vault_withdrawn_handle: account::new_event_handle<Coin_claimer_1_VaultWithdrawn>(&res_account),
            coin_claimer_1_vault_admin_withdrawn_handle: account::new_event_handle<Coin_claimer_1_VaultAdminWithdrawn>(&res_account),
        });

        let aptos_forms_demo2_global = new_aptos_forms_demo2_global();
        add_aptos_forms_demo2_global(aptos_forms_demo2_global);
    }

    struct AptosFormsDemo2Global has key, store {
        version: u64,
        coin_claimer_1_vault: Coin<AptosCoin>,
        coin_claimer_1_total_shares: u64,
        coin_claimer_1_claimed_count: u64,
    }

    public fun version(aptos_forms_demo2_global: &AptosFormsDemo2Global): u64 {
        aptos_forms_demo2_global.version
    }

    public fun borrow_coin_claimer_1_vault(aptos_forms_demo2_global: &AptosFormsDemo2Global): &Coin<AptosCoin> {
        &aptos_forms_demo2_global.coin_claimer_1_vault
    }

    public(friend) fun borrow_mut_coin_claimer_1_vault(aptos_forms_demo2_global: &mut AptosFormsDemo2Global): &mut Coin<AptosCoin> {
        &mut aptos_forms_demo2_global.coin_claimer_1_vault
    }

    public fun coin_claimer_1_total_shares(aptos_forms_demo2_global: &AptosFormsDemo2Global): u64 {
        aptos_forms_demo2_global.coin_claimer_1_total_shares
    }

    public(friend) fun set_coin_claimer_1_total_shares(aptos_forms_demo2_global: &mut AptosFormsDemo2Global, coin_claimer_1_total_shares: u64) {
        aptos_forms_demo2_global.coin_claimer_1_total_shares = coin_claimer_1_total_shares;
    }

    public fun coin_claimer_1_claimed_count(aptos_forms_demo2_global: &AptosFormsDemo2Global): u64 {
        aptos_forms_demo2_global.coin_claimer_1_claimed_count
    }

    public(friend) fun set_coin_claimer_1_claimed_count(aptos_forms_demo2_global: &mut AptosFormsDemo2Global, coin_claimer_1_claimed_count: u64) {
        aptos_forms_demo2_global.coin_claimer_1_claimed_count = coin_claimer_1_claimed_count;
    }

    public(friend) fun new_aptos_forms_demo2_global(
    ): AptosFormsDemo2Global {
        AptosFormsDemo2Global {
            version: 0,
            coin_claimer_1_vault: aptos_framework::coin::zero(),
            coin_claimer_1_total_shares: 10,
            coin_claimer_1_claimed_count: 0,
        }
    }

    struct Coin_claimer_1_VaultDeposited has store, drop {
        version: u64,
        amount: u64,
    }

    public fun coin_claimer_1_vault_deposited_amount(coin_claimer_1_vault_deposited: &Coin_claimer_1_VaultDeposited): u64 {
        coin_claimer_1_vault_deposited.amount
    }

    public(friend) fun new_coin_claimer_1_vault_deposited(
        aptos_forms_demo2_global: &AptosFormsDemo2Global,
        amount: u64,
    ): Coin_claimer_1_VaultDeposited {
        Coin_claimer_1_VaultDeposited {
            version: version(aptos_forms_demo2_global),
            amount,
        }
    }

    struct Coin_claimer_1_VaultWithdrawn has store, drop {
        version: u64,
        amount: u64,
    }

    public fun coin_claimer_1_vault_withdrawn_amount(coin_claimer_1_vault_withdrawn: &Coin_claimer_1_VaultWithdrawn): u64 {
        coin_claimer_1_vault_withdrawn.amount
    }

    public(friend) fun new_coin_claimer_1_vault_withdrawn(
        aptos_forms_demo2_global: &AptosFormsDemo2Global,
        amount: u64,
    ): Coin_claimer_1_VaultWithdrawn {
        Coin_claimer_1_VaultWithdrawn {
            version: version(aptos_forms_demo2_global),
            amount,
        }
    }

    struct Coin_claimer_1_VaultAdminWithdrawn has store, drop {
        version: u64,
        amount: u64,
    }

    public fun coin_claimer_1_vault_admin_withdrawn_amount(coin_claimer_1_vault_admin_withdrawn: &Coin_claimer_1_VaultAdminWithdrawn): u64 {
        coin_claimer_1_vault_admin_withdrawn.amount
    }

    public(friend) fun new_coin_claimer_1_vault_admin_withdrawn(
        aptos_forms_demo2_global: &AptosFormsDemo2Global,
        amount: u64,
    ): Coin_claimer_1_VaultAdminWithdrawn {
        Coin_claimer_1_VaultAdminWithdrawn {
            version: version(aptos_forms_demo2_global),
            amount,
        }
    }

    struct AptosFormsDemo2GlobalInitialized has store, drop {
    }

    public(friend) fun new_aptos_forms_demo2_global_initialized(
        aptos_forms_demo2_global: &AptosFormsDemo2Global,
    ): AptosFormsDemo2GlobalInitialized {
        AptosFormsDemo2GlobalInitialized {
        }
    }


    public(friend) fun update_version_and_add(aptos_forms_demo2_global: AptosFormsDemo2Global) {
        aptos_forms_demo2_global.version = aptos_forms_demo2_global.version + 1;
        //assert!(aptos_forms_demo2_global.version != 0, EInappropriateVersion);
        private_add_aptos_forms_demo2_global(aptos_forms_demo2_global);
    }

    public(friend) fun add_aptos_forms_demo2_global(aptos_forms_demo2_global: AptosFormsDemo2Global) {
        assert!(aptos_forms_demo2_global.version == 0, EInappropriateVersion);
        private_add_aptos_forms_demo2_global(aptos_forms_demo2_global);
    }

    public(friend) fun remove_aptos_forms_demo2_global(): AptosFormsDemo2Global acquires AptosFormsDemo2Global {
        assert!(exists<AptosFormsDemo2Global>(genesis_account::resource_account_address()), ENotInitialized);
        move_from<AptosFormsDemo2Global>(genesis_account::resource_account_address())
    }

    fun private_add_aptos_forms_demo2_global(aptos_forms_demo2_global: AptosFormsDemo2Global) {
        move_to(&genesis_account::resource_account_signer(), aptos_forms_demo2_global);
    }

    public fun get_aptos_forms_demo2_global(): pass_object::PassObject<AptosFormsDemo2Global> acquires AptosFormsDemo2Global {
        let aptos_forms_demo2_global = remove_aptos_forms_demo2_global();
        pass_object::new(aptos_forms_demo2_global)
    }

    public fun singleton_coin_claimer_1_total_shares(): u64 acquires AptosFormsDemo2Global {
        let aptos_forms_demo2_global = borrow_global<AptosFormsDemo2Global>(genesis_account::resource_account_address());
        aptos_forms_demo2_global.coin_claimer_1_total_shares
    }

    public fun singleton_coin_claimer_1_claimed_count(): u64 acquires AptosFormsDemo2Global {
        let aptos_forms_demo2_global = borrow_global<AptosFormsDemo2Global>(genesis_account::resource_account_address());
        aptos_forms_demo2_global.coin_claimer_1_claimed_count
    }

    public fun return_aptos_forms_demo2_global(aptos_forms_demo2_global_pass_obj: pass_object::PassObject<AptosFormsDemo2Global>) {
        let aptos_forms_demo2_global = pass_object::extract(aptos_forms_demo2_global_pass_obj);
        private_add_aptos_forms_demo2_global(aptos_forms_demo2_global);
    }

    public(friend) fun drop_aptos_forms_demo2_global(aptos_forms_demo2_global: AptosFormsDemo2Global) {
        let AptosFormsDemo2Global {
            version: _version,
            coin_claimer_1_vault,
            coin_claimer_1_total_shares: _coin_claimer_1_total_shares,
            coin_claimer_1_claimed_count: _coin_claimer_1_claimed_count,
        } = aptos_forms_demo2_global;
        aptos_framework::coin::destroy_zero(coin_claimer_1_vault);
    }

    public fun aptos_forms_demo2_global_exists(): bool {
        exists<AptosFormsDemo2Global>(genesis_account::resource_account_address())
    }

    public(friend) fun emit_coin_claimer_1_vault_deposited(coin_claimer_1_vault_deposited: Coin_claimer_1_VaultDeposited) acquires Events {
        assert!(exists<Events>(genesis_account::resource_account_address()), ENotInitialized);
        let events = borrow_global_mut<Events>(genesis_account::resource_account_address());
        event::emit_event(&mut events.coin_claimer_1_vault_deposited_handle, coin_claimer_1_vault_deposited);
    }

    public(friend) fun emit_coin_claimer_1_vault_withdrawn(coin_claimer_1_vault_withdrawn: Coin_claimer_1_VaultWithdrawn) acquires Events {
        assert!(exists<Events>(genesis_account::resource_account_address()), ENotInitialized);
        let events = borrow_global_mut<Events>(genesis_account::resource_account_address());
        event::emit_event(&mut events.coin_claimer_1_vault_withdrawn_handle, coin_claimer_1_vault_withdrawn);
    }

    public(friend) fun emit_coin_claimer_1_vault_admin_withdrawn(coin_claimer_1_vault_admin_withdrawn: Coin_claimer_1_VaultAdminWithdrawn) acquires Events {
        assert!(exists<Events>(genesis_account::resource_account_address()), ENotInitialized);
        let events = borrow_global_mut<Events>(genesis_account::resource_account_address());
        event::emit_event(&mut events.coin_claimer_1_vault_admin_withdrawn_handle, coin_claimer_1_vault_admin_withdrawn);
    }

}
