// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_forms_demo::aptos_forms_demo_main_form_submitted {

    use aptos_forms_demo::aptos_forms_demo_main_form::{Self, AptosFormsDemoMainFormSubmitted};
    use std::string::String;
    use xrender_form_utils::string_range::StringRange;

    public fun signer_address(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): address {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_signer_address(aptos_forms_demo_main_form_submitted)
    }

    public fun fr_5pqi(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): u128 {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_fr_5pqi(aptos_forms_demo_main_form_submitted)
    }

    public fun fr_duif(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): vector<String> {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_fr_duif(aptos_forms_demo_main_form_submitted)
    }

    public fun fr_6i34(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): vector<String> {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_fr_6i34(aptos_forms_demo_main_form_submitted)
    }

    public fun fr_8xjs(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): String {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_fr_8xjs(aptos_forms_demo_main_form_submitted)
    }

    public fun fr_9c3f(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): String {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_fr_9c3f(aptos_forms_demo_main_form_submitted)
    }

    public fun fr_4ok6(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): u128 {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_fr_4ok6(aptos_forms_demo_main_form_submitted)
    }

    public fun fr_b3ub(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): String {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_fr_b3ub(aptos_forms_demo_main_form_submitted)
    }

    public fun fr_1z7o(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): u128 {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_fr_1z7o(aptos_forms_demo_main_form_submitted)
    }

    public fun fr_d8rw(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): StringRange {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_fr_d8rw(aptos_forms_demo_main_form_submitted)
    }

    public fun fr_dy3l(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): StringRange {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_fr_dy3l(aptos_forms_demo_main_form_submitted)
    }

    public fun fr_6f68(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): u128 {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_fr_6f68(aptos_forms_demo_main_form_submitted)
    }

    public fun fr_47yy(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): StringRange {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_fr_47yy(aptos_forms_demo_main_form_submitted)
    }

    public fun fr_gh3o(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): vector<String> {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_fr_gh3o(aptos_forms_demo_main_form_submitted)
    }

    public fun fr_fbba(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): vector<String> {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_fr_fbba(aptos_forms_demo_main_form_submitted)
    }

    public fun fr_hhzp(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): String {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_fr_hhzp(aptos_forms_demo_main_form_submitted)
    }

    public fun single_text1(aptos_forms_demo_main_form_submitted: &AptosFormsDemoMainFormSubmitted): String {
        aptos_forms_demo_main_form::aptos_forms_demo_main_form_submitted_single_text1(aptos_forms_demo_main_form_submitted)
    }

}
