// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_forms_demo::aptos_forms_demo_coin_claimer_1_aggregate {
    use aptos_forms_demo::aptos_forms_demo_coin_claimer_1;
    use aptos_forms_demo::aptos_forms_demo_coin_claimer_1_claim_logic;

    public entry fun claim(
        account: &signer,
    ) {
        let aptos_forms_demo_coin_claimer_1_claimed = aptos_forms_demo_coin_claimer_1_claim_logic::verify(
            account,
        );
        let aptos_forms_demo_coin_claimer_1 = aptos_forms_demo_coin_claimer_1_claim_logic::mutate(
            account,
            &aptos_forms_demo_coin_claimer_1_claimed,
        );
        aptos_forms_demo_coin_claimer_1::add_aptos_forms_demo_coin_claimer_1(aptos_forms_demo_coin_claimer_1);
        aptos_forms_demo_coin_claimer_1::emit_aptos_forms_demo_coin_claimer_1_claimed(aptos_forms_demo_coin_claimer_1_claimed);
    }

}
