// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_forms_demo::aptos_forms_demo_main_form_aggregate {
    use aptos_forms_demo::aptos_forms_demo_main_form;
    use aptos_forms_demo::aptos_forms_demo_main_form_submit_logic;
    use std::string::String;

    public entry fun submit(
        account: &signer,
        fr_5pqi: u128,
        aptos_forms_demo_fr_duif: vector<String>,
        aptos_forms_demo_fr_6i34: vector<String>,
        fr_8xjs: String,
        aptos_forms_demo_fr_9c3f: String,
        fr_4ok6: u128,
        fr_b3ub: String,
        fr_1z7o: u128,
        fr_d8rw: vector<std::string::String>,
        fr_dy3l: vector<std::string::String>,
        fr_6f68: u128,
        fr_47yy: vector<std::string::String>,
        aptos_forms_demo_fr_gh3o: vector<String>,
        aptos_forms_demo_fr_fbba: vector<String>,
        fr_hhzp: String,
        single_text1: String,
    ) {
        let aptos_forms_demo_main_form_submitted = aptos_forms_demo_main_form_submit_logic::verify(
            account,
            fr_5pqi,
            aptos_forms_demo_fr_duif,
            aptos_forms_demo_fr_6i34,
            fr_8xjs,
            aptos_forms_demo_fr_9c3f,
            fr_4ok6,
            fr_b3ub,
            fr_1z7o,
            xrender_form_utils::string_range::value_of(fr_d8rw),
            xrender_form_utils::string_range::value_of(fr_dy3l),
            fr_6f68,
            xrender_form_utils::string_range::value_of(fr_47yy),
            aptos_forms_demo_fr_gh3o,
            aptos_forms_demo_fr_fbba,
            fr_hhzp,
            single_text1,
        );
        let aptos_forms_demo_main_form = aptos_forms_demo_main_form_submit_logic::mutate(
            account,
            &aptos_forms_demo_main_form_submitted,
        );
        aptos_forms_demo_main_form::add_aptos_forms_demo_main_form(aptos_forms_demo_main_form);
        aptos_forms_demo_main_form::emit_aptos_forms_demo_main_form_submitted(aptos_forms_demo_main_form_submitted);
    }

}
