// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_forms_demo::aptos_forms_demo2_global_aggregate {
    use aptos_forms_demo::aptos_forms_demo2_global;
    use aptos_forms_demo::aptos_forms_demo2_global_admin_withdraw_coin_claimer_1_vault_logic;
    use aptos_forms_demo::aptos_forms_demo2_global_deposit_coin_claimer_1_vault_logic;
    use aptos_forms_demo::aptos_forms_demo2_global_withdraw_coin_claimer_1_vault_logic;
    use aptos_framework::aptos_coin::AptosCoin;
    use aptos_framework::coin::Coin;

    friend aptos_forms_demo::aptos_forms_demo2_coin_claimer_1_claim_logic;

    public entry fun deposit_coin_claimer_1_vault(
        account: &signer,
        amount: u64,
    ) {
        let aptos_forms_demo2_global = aptos_forms_demo2_global::remove_aptos_forms_demo2_global();
        let coin_claimer_1_vault_deposited = aptos_forms_demo2_global_deposit_coin_claimer_1_vault_logic::verify(
            account,
            amount,
            &aptos_forms_demo2_global,
        );
        let updated_aptos_forms_demo2_global = aptos_forms_demo2_global_deposit_coin_claimer_1_vault_logic::mutate(
            account,
            &coin_claimer_1_vault_deposited,
            aptos_forms_demo2_global,
        );
        aptos_forms_demo2_global::update_version_and_add(updated_aptos_forms_demo2_global);
        aptos_forms_demo2_global::emit_coin_claimer_1_vault_deposited(coin_claimer_1_vault_deposited);
    }

    public(friend) fun withdraw_coin_claimer_1_vault(
        account: &signer,
        amount: u64,
    ): Coin<AptosCoin> {
        let aptos_forms_demo2_global = aptos_forms_demo2_global::remove_aptos_forms_demo2_global();
        let coin_claimer_1_vault_withdrawn = aptos_forms_demo2_global_withdraw_coin_claimer_1_vault_logic::verify(
            account,
            amount,
            &aptos_forms_demo2_global,
        );
        let (updated_aptos_forms_demo2_global, withdraw_coin_claimer_1_vault_return) = aptos_forms_demo2_global_withdraw_coin_claimer_1_vault_logic::mutate(
            account,
            &coin_claimer_1_vault_withdrawn,
            aptos_forms_demo2_global,
        );
        aptos_forms_demo2_global::update_version_and_add(updated_aptos_forms_demo2_global);
        aptos_forms_demo2_global::emit_coin_claimer_1_vault_withdrawn(coin_claimer_1_vault_withdrawn);
        withdraw_coin_claimer_1_vault_return
    }

    public entry fun admin_withdraw_coin_claimer_1_vault(
        account: &signer,
        amount: u64,
    ) {
        let aptos_forms_demo2_global = aptos_forms_demo2_global::remove_aptos_forms_demo2_global();
        let coin_claimer_1_vault_admin_withdrawn = aptos_forms_demo2_global_admin_withdraw_coin_claimer_1_vault_logic::verify(
            account,
            amount,
            &aptos_forms_demo2_global,
        );
        let updated_aptos_forms_demo2_global = aptos_forms_demo2_global_admin_withdraw_coin_claimer_1_vault_logic::mutate(
            account,
            &coin_claimer_1_vault_admin_withdrawn,
            aptos_forms_demo2_global,
        );
        aptos_forms_demo2_global::update_version_and_add(updated_aptos_forms_demo2_global);
        aptos_forms_demo2_global::emit_coin_claimer_1_vault_admin_withdrawn(coin_claimer_1_vault_admin_withdrawn);
    }

}
