// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

//
// WithdrawCoin_claimer_1_Vault event module is disabled.
// Use aptos_forms_demo_global module instead.
//
