// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_forms_demo::fr_6i34 {
    use std::string::{Self, String};
    use std::vector;

    public fun a(): String {
        string::utf8(b"A")
    }

    public fun b(): String {
        string::utf8(b"B")
    }

    public fun c(): String {
        string::utf8(b"C")
    }

    public fun is_valid(v: String): bool {
        v == a() || v == b() || v == c()
    }

    public fun are_all_valid(vs: &vector<String>): bool {
        let i = 0;
        let l = vector::length(vs);
        while (i < l) {
            if (!is_valid(*vector::borrow(vs, i))) {
                return false
            };
            i = i + 1;
        };
        true
    }
}
