// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_forms_demo::main_form_created {

    use aptos_forms_demo::main_form::{Self, MainFormCreated};
    use std::string::String;

    public fun account_address(main_form_created: &MainFormCreated): address {
        main_form::main_form_created_account_address(main_form_created)
    }

    public fun fr_5pqi(main_form_created: &MainFormCreated): u128 {
        main_form::main_form_created_fr_5pqi(main_form_created)
    }

    public fun fr_duif(main_form_created: &MainFormCreated): vector<String> {
        main_form::main_form_created_fr_duif(main_form_created)
    }

    public fun fr_6i34(main_form_created: &MainFormCreated): vector<String> {
        main_form::main_form_created_fr_6i34(main_form_created)
    }

    public fun fr_8xjs(main_form_created: &MainFormCreated): String {
        main_form::main_form_created_fr_8xjs(main_form_created)
    }

    public fun fr_9c3f(main_form_created: &MainFormCreated): String {
        main_form::main_form_created_fr_9c3f(main_form_created)
    }

    public fun fr_4ok6(main_form_created: &MainFormCreated): u128 {
        main_form::main_form_created_fr_4ok6(main_form_created)
    }

    public fun fr_b3ub(main_form_created: &MainFormCreated): String {
        main_form::main_form_created_fr_b3ub(main_form_created)
    }

    public fun fr_1z7o(main_form_created: &MainFormCreated): u128 {
        main_form::main_form_created_fr_1z7o(main_form_created)
    }

    public fun fr_6f68(main_form_created: &MainFormCreated): u128 {
        main_form::main_form_created_fr_6f68(main_form_created)
    }

    public fun fr_gh3o(main_form_created: &MainFormCreated): vector<String> {
        main_form::main_form_created_fr_gh3o(main_form_created)
    }

    public fun fr_fbba(main_form_created: &MainFormCreated): vector<String> {
        main_form::main_form_created_fr_fbba(main_form_created)
    }

    public fun fr_hhzp(main_form_created: &MainFormCreated): String {
        main_form::main_form_created_fr_hhzp(main_form_created)
    }

    public fun single_text1(main_form_created: &MainFormCreated): String {
        main_form::main_form_created_single_text1(main_form_created)
    }

}
