// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_forms_demo::main_form_submitted {

    use aptos_forms_demo::main_form::{Self, MainFormSubmitted};
    use std::string::String;
    use xrender_form_utils::string_range::StringRange;

    public fun signer_address(main_form_submitted: &MainFormSubmitted): address {
        main_form::main_form_submitted_signer_address(main_form_submitted)
    }

    public fun fr_5pqi(main_form_submitted: &MainFormSubmitted): u128 {
        main_form::main_form_submitted_fr_5pqi(main_form_submitted)
    }

    public fun fr_duif(main_form_submitted: &MainFormSubmitted): vector<String> {
        main_form::main_form_submitted_fr_duif(main_form_submitted)
    }

    public fun fr_6i34(main_form_submitted: &MainFormSubmitted): vector<String> {
        main_form::main_form_submitted_fr_6i34(main_form_submitted)
    }

    public fun fr_8xjs(main_form_submitted: &MainFormSubmitted): String {
        main_form::main_form_submitted_fr_8xjs(main_form_submitted)
    }

    public fun fr_9c3f(main_form_submitted: &MainFormSubmitted): String {
        main_form::main_form_submitted_fr_9c3f(main_form_submitted)
    }

    public fun fr_4ok6(main_form_submitted: &MainFormSubmitted): u128 {
        main_form::main_form_submitted_fr_4ok6(main_form_submitted)
    }

    public fun fr_b3ub(main_form_submitted: &MainFormSubmitted): String {
        main_form::main_form_submitted_fr_b3ub(main_form_submitted)
    }

    public fun fr_1z7o(main_form_submitted: &MainFormSubmitted): u128 {
        main_form::main_form_submitted_fr_1z7o(main_form_submitted)
    }

    public fun fr_d8rw(main_form_submitted: &MainFormSubmitted): StringRange {
        main_form::main_form_submitted_fr_d8rw(main_form_submitted)
    }

    public fun fr_dy3l(main_form_submitted: &MainFormSubmitted): StringRange {
        main_form::main_form_submitted_fr_dy3l(main_form_submitted)
    }

    public fun fr_6f68(main_form_submitted: &MainFormSubmitted): u128 {
        main_form::main_form_submitted_fr_6f68(main_form_submitted)
    }

    public fun fr_47yy(main_form_submitted: &MainFormSubmitted): StringRange {
        main_form::main_form_submitted_fr_47yy(main_form_submitted)
    }

    public fun fr_gh3o(main_form_submitted: &MainFormSubmitted): vector<String> {
        main_form::main_form_submitted_fr_gh3o(main_form_submitted)
    }

    public fun fr_fbba(main_form_submitted: &MainFormSubmitted): vector<String> {
        main_form::main_form_submitted_fr_fbba(main_form_submitted)
    }

    public fun fr_hhzp(main_form_submitted: &MainFormSubmitted): String {
        main_form::main_form_submitted_fr_hhzp(main_form_submitted)
    }

    public fun single_text1(main_form_submitted: &MainFormSubmitted): String {
        main_form::main_form_submitted_single_text1(main_form_submitted)
    }

}
