// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_forms_demo::payment_123_vault_withdrawn {

    use aptos_forms_demo::aptos_forms_demo_global::{Self, Payment_123_VaultWithdrawn};

    public fun amount(payment_123_vault_withdrawn: &Payment_123_VaultWithdrawn): u64 {
        aptos_forms_demo_global::payment_123_vault_withdrawn_amount(payment_123_vault_withdrawn)
    }

}
