// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_forms_demo::payment_123_vault_deposited {

    use aptos_forms_demo::aptos_forms_demo_global::{Self, Payment_123_VaultDeposited};

    public fun amount(payment_123_vault_deposited: &Payment_123_VaultDeposited): u64 {
        aptos_forms_demo_global::payment_123_vault_deposited_amount(payment_123_vault_deposited)
    }

}
