spring:
  datasource:
#    url: jdbc:mysql://localhost/test2?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
#    username: root
#    password: 123456
    url: jdbc:postgresql://localhost:5432/test2
    username: postgres
    password: 123456

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update

server:
  port: 1023

aptos:
  contract:
    # TestNet
#    address:
#      "0xf0ee3187beaa48e56def59dbe52d7e932c3e559c28ae26568fa91ff9ae85e145"
    address:
      "0x56c01bfdfae128e57544f59f52be70bb883ea2d1fb97ba5774741996f77b4eb7"
    node-api:
      #base-url: "https://fullnode.testnet.aptoslabs.com/v1"
      base-url: "https://fullnode.devnet.aptoslabs.com/v1"
    pull-aptos-forms-demo-coin-claimer-1-events:
      aptos-forms-demo-coin-claimer-1-claimed:
        fixed-delay: 60000
    pull-aptos-forms-demo-global-events:
      payment-123-vault-deposited:
        fixed-delay: 60000
      payment-123-vault-withdrawn:
        fixed-delay: 60000
      payment-123-vault-admin-withdrawn:
        fixed-delay: 60000
      coin-claimer-1-vault-deposited:
        fixed-delay: 60000
      coin-claimer-1-vault-withdrawn:
        fixed-delay: 60000
      coin-claimer-1-vault-admin-withdrawn:
        fixed-delay: 60000
    pull-aptos-forms-demo-main-form-events:
      aptos-forms-demo-main-form-submitted:
        fixed-delay: 60000
      aptos-forms-demo-main-form-updated:
        fixed-delay: 60000
    update-aptos-forms-demo-coin-claimer-1-states:
      fixed-delay: 60000
    update-aptos-forms-demo-global-states:
      fixed-delay: 60000
    update-aptos-forms-demo-main-form-states:
      fixed-delay: 60000


  cli:
    path: "/Users/yangjiefeng/.cargo/bin/aptos"


dddappp:
  project-creation-service:
    url: "http://ec2-35-165-219-121.us-west-2.compute.amazonaws.com:5000/ProjectTools/CreateProject"

logging:
  level:
    org:
      springframework:
        web: DEBUG
